### PR TITLE
add support for CUSA05877 (US Persona 5)

### PR DESCRIPTION
**Pull request by Whitehawkx**
This adds full support for the US version of Persona 5. All patches from the EU version have been ported. I don't believe the all_dlc patch is needed on this version, so I skipped that one. The block of code the EU version nop's isn't present in the US version. I tested that all patches applied properly and game boots. I tested functionality for everything except zzz and env, but those were pretty simple patches. Also included a skeleton zip to match the other versions for building an update pkg.

Update: Added a new share_button.xdelta patch that enables video recording and screenshots using the share button. Only applicable for vanilla P5. Included for both CUSA05877 and CUSA06638.

### CODE REVIEW

**Comment by zarroboogs** [comment]
Thanks 👍

Regarding the `all_dlc` patch, it's only required if you want to activate all DLCs without having to install unlock pkgs.
The only DLC that actually has to be installed is JP voices (it contains the archive with the JP audio files).

Regarding the `share_button` patch - isn't that usually enabled globally with HEN?
That's how it works with GoldHEN, at least.
~~You've also added it to the output example in the README, but the output is for P5R~~ 😳

**Comment by Whitehawkx** [comment]
I can look into the `all_dlc` patch. Seems to be different from the EU version.

Regarding the `share_button` patch - on 9.00 with GoldHen screenshots worked but video recording was still blocked. Was able to resolve that with the patch though. I just went ahead and included the screenshots in it as well just in case cutscenes still blocked them.

**Comment by zarroboogs** [comment]
It looks like it's an issue with GoldHEN on 9.00 in general since it also happens in P5R according to some users. I guess I'll add a patch for that soon.

Anyway, merged 😄

**Comment by u2716** [comment]
@zarroboogs do you have any plans to port your persona patches to goldhen?
Now goldhen supports applying patches to the eboot without rebuilding fpkgs (https://github.com/GoldHEN/GoldHEN_Patch_Repository), making it a lot more easier to apply patches.

Thank you for your work btw :)

**Pull request merged**
